import type { NextPage } from 'next'
import useSWR from 'swr';
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

import { Box } from '@mui/system';
import { Card, CardContent, Typography, Skeleton, IconButton, Stack } from '@mui/material';
import ReplayCircleFilledIcon from '@mui/icons-material/ReplayCircleFilled';

const quranRandomizer = 'http://quran-randomizer.herokuapp.com/'
const getAyah = async () => {
  const response = await fetch(quranRandomizer);
  return await response.json();
}

const Ayah = () => {
  const { data, error, mutate, isValidating } = useSWR(quranRandomizer, getAyah);

  function handleClick() {
    mutate(quranRandomizer)
  }

  return (
    <Card sx={{ minWidth: 275 }}>
      { isValidating ? <Skeleton /> :
        <CardContent>
          <Typography sx={{ fontSize: 14, mb: 2 }}>
            {data.resources.nameOfSurah.transliteration.id} : {data.resources.numberOfAyah}
          </Typography>
          <Typography variant="h5" component="div" align='right'>
            {data.resources.ayah.text.arab}
          </Typography>
          <Typography sx={{ mb: 1.5 }} color="text.secondary">
            {data.resources.ayah.translation.id}
          </Typography>
        </CardContent>
      }
      <Stack spacing={3}>
          <IconButton size="large" onClick={handleClick} aria-label='refresh' color='success'>
              <ReplayCircleFilledIcon fontSize='inherit'/>
          </IconButton>
      </Stack>
    </Card>
  )
}

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Box sx={{ width: '80%',
                  margin:'auto'}}>
          <Ayah />
        </Box>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}

export default Home
