import type { NextPage } from 'next'
import useSWR from 'swr';
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

import { Box } from '@mui/system';
import { Card, CardActions, CardContent, Button, Typography, CircularProgress } from '@mui/material';

const quranRandomizer = 'http://quran-randomizer.herokuapp.com/'
const getAyah = async () => {
  const response = await fetch(quranRandomizer);
  return await response.json();
}

const Ayah = () => {
  const { data, error } = useSWR(quranRandomizer, getAyah);
  if (error) return <div>Failed to load</div>
  if (!data)return <CircularProgress/>

  const { resources } = data;

  return (
    <Card sx={{ minWidth: 275 }}>
      <CardContent>
        <Typography sx={{ fontSize: 14 }}>
          {resources.nameOfSurah.transliteration.id} : {resources.numberOfAyah}
        </Typography>
        <Typography variant="h5" component="div" align='right'>
          {resources.ayah.text.arab}
        </Typography>
        <Typography sx={{ mb: 1.5 }} color="text.secondary">
          {resources.ayah.translation.id}
        </Typography>
      </CardContent>
      <CardActions>
        <Button size="small">Learn More</Button>
      </CardActions>
    </Card>
  )
}

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Box sx={{ width: '80%',
                  margin:'auto'}}>
          <Ayah />
        </Box>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}

export default Home
